package frc.trigon.robot.misc.shootingphysics;

import org.littletonrobotics.junction.networktables.LoggedNetworkNumber;

import java.io.*;

/**
 * 3D shooting lookup table using trilinear interpolation.
 * Precomputed trajectory solutions indexed by distance and robot velocity.
 * Generated by Python calibration system - loads binary data at runtime.
 * <p>
 * Uses division counts (integers) for index calculation to avoid floating point drift.
 */
public class ShootingLookupTable3D {
    private static final int BUFFER_SIZE = 65536;
    private static final int BYTES_PER_DOUBLE = 8;
    private static final int BYTES_PER_MEGABYTE = 1024 * 1024;
    private static final double SYMMETRY_THRESHOLD = 0.0;

    private static int distanceDivisions;
    private static int velocityDivisions;
    private static int distanceSize;
    private static int radialSize;
    private static int tangentialSize;

    private static double distanceMin;
    private static double distanceMax;
    private static double radialMin;
    private static double radialMax;
    private static double tangentialMin;
    private static double tangentialMax;

    private static double[] velocityData;
    private static double[] pitchData;
    private static double[] yawData;

    private static boolean isLoaded = false;

    public static void init() {
        try {
            loadFromFile(ShootingCalculationsConstants.SHOOTING_LOOKUP_TABLE_FILEPATH, true);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void loadFromFile(final String filepath, final boolean verbose) throws IOException {
        if (isLoaded) {
            logIfVerbose("ShootingLookupTable3D already loaded, skipping", verbose);
            return;
        }

        validateFileExists(filepath);
        final long startTime = System.currentTimeMillis();

        loadTableData(filepath, verbose);

        isLoaded = true;
        logLoadingComplete(startTime, verbose);
    }

    public static boolean isLoaded() {
        return isLoaded && velocityData != null && velocityData.length > 0;
    }

    private static LoggedNetworkNumber velSlopeConst = new LoggedNetworkNumber("/SmartDashboard/ShootingLookupTable3D/VelocitySlopeConstant", 1.34);
    private static LoggedNetworkNumber velInterceptConst = new LoggedNetworkNumber("/SmartDashboard/ShootingLookupTable3D/VelocityInterceptConstant", 1.32);
    private static LoggedNetworkNumber pitConst = new LoggedNetworkNumber("/SmartDashboard/ShootingLookupTable3D/PitchConstant", 1);

    public static double calculateVelocity(final double distance, final double radialVelocity, final double tangentialVelocity) {
        validateLoaded();
        return calcActualVel(interpolate(velocityData, distance, radialVelocity, Math.abs(tangentialVelocity)));
    }

    private static double calcActualVel(double velWanted) {
        return velSlopeConst.get() * velWanted;
    }

    public static double calculatePitch(final double distance, final double radialVelocity, final double tangentialVelocity) {
        validateLoaded();
        return calcActualPit(interpolate(pitchData, distance, radialVelocity, Math.abs(tangentialVelocity)));
    }

    private static double calcActualPit(double pitWanted) {
//        final double rotorVel = RobotContainer.SHOOTER.getTargetVelocityMetersPerSecond() * ShooterConstants.GEAR_RATIO;
//        final double velDifference = rotorVel * (ShooterConstants.LOWER_WHEEL_ROTATIONS_PER_METER - ShooterConstants.UPPER_WHEEL_ROTATIONS_PER_METER);
//        Logger.recordOutput("Shooting/VelocityDifference", velDifference);
//        Logger.recordOutput("Shooting/AngleAdditionDegrees", Math.toDegrees(Math.toRadians(pitConst.get()) * velDifference));
//        return (Math.toRadians(pitConst.get()) * velDifference) + pitWanted;
        return Math.toRadians(pitConst.get()) + pitWanted;
    }

    public static double calculateYaw(final double distance, final double radialVelocity, final double tangentialVelocity) {
        validateLoaded();
        final double yaw = interpolate(yawData, distance, radialVelocity, Math.abs(tangentialVelocity));
        return applyYawSymmetry(yaw, tangentialVelocity);
    }

    private static void validateFileExists(final String filepath) throws IOException {
        final File file = new File(filepath);
        if (!file.exists()) {
            throw new IOException("LUT file not found: " + filepath);
        }
    }

    private static void validateLoaded() {
        if (!isLoaded()) {
            throw new IllegalStateException("ShootingLookupTable3D not loaded!");
        }
    }

    private static void loadTableData(final String filepath, final boolean verbose) throws IOException {
        try (final DataInputStream stream = createInputStream(filepath)) {
            logLoadingStart(filepath, verbose);

            readHeader(stream);
            readShootingData(stream, verbose);

        } catch (final IOException e) {
            System.err.println("ERROR loading ShootingLookupTable3D: " + e.getMessage());
            throw e;
        }
    }

    private static DataInputStream createInputStream(final String filepath) throws IOException {
        final FileInputStream fileStream = new FileInputStream(filepath);
        final BufferedInputStream bufferedStream = new BufferedInputStream(fileStream, BUFFER_SIZE);
        return new DataInputStream(bufferedStream);
    }

    private static void readHeader(final DataInputStream stream) throws IOException {
        readDivisions(stream);
        calculateGridSizes();
        readBounds(stream);
    }

    private static void readDivisions(final DataInputStream stream) throws IOException {
        distanceDivisions = stream.readInt();
        velocityDivisions = stream.readInt();
        stream.readInt(); // reserved
    }

    private static void calculateGridSizes() {
        distanceSize = distanceDivisions + 1;
        radialSize = 2 * velocityDivisions + 1;
        tangentialSize = velocityDivisions + 1;
    }

    private static void readBounds(final DataInputStream stream) throws IOException {
        distanceMin = stream.readDouble();
        distanceMax = stream.readDouble();
        radialMin = stream.readDouble();
        radialMax = stream.readDouble();
        tangentialMin = stream.readDouble();
        tangentialMax = stream.readDouble();
    }

    private static void readShootingData(final DataInputStream stream, final boolean verbose) throws IOException {
        final int totalElements = calculateTotalElements();

        if (verbose) {
            logGridDimensions(totalElements);
        }

        velocityData = readDoubleArray(stream, totalElements);
        pitchData = readDoubleArray(stream, totalElements);
        yawData = readDoubleArray(stream, totalElements);
    }

    private static double[] readDoubleArray(final DataInputStream stream, final int size) throws IOException {
        final double[] array = new double[size];
        for (int i = 0; i < size; i++) {
            array[i] = stream.readDouble();
        }
        return array;
    }

    private static double interpolate(final double[] data, final double distance, final double radialVelocity, final double tangentialVelocity) {
        final double clampedDistance = clamp(distance, distanceMin, distanceMax);
        final double clampedRadial = clamp(radialVelocity, radialMin, radialMax);
        final double clampedTangential = clamp(tangentialVelocity, tangentialMin, tangentialMax);

        final double distanceIndex = calculateIndex(clampedDistance, distanceMin, distanceMax, distanceDivisions);
        final double radialIndex = calculateIndex(clampedRadial, radialMin, radialMax, 2 * velocityDivisions);
        final double tangentialIndex = calculateIndex(clampedTangential, tangentialMin, tangentialMax, velocityDivisions);

        return trilinearInterpolate(data, distanceIndex, radialIndex, tangentialIndex);
    }

    private static double calculateIndex(final double value, final double min, final double max, final int divisions) {
        final double normalized = (value - min) / (max - min);
        return normalized * divisions;
    }

    private static double trilinearInterpolate(final double[] data, final double distanceIndex, final double radialIndex, final double tangentialIndex) {
        final int d0 = (int) Math.floor(distanceIndex);
        final int d1 = Math.min(d0 + 1, distanceSize - 1);
        final int r0 = (int) Math.floor(radialIndex);
        final int r1 = Math.min(r0 + 1, radialSize - 1);
        final int t0 = (int) Math.floor(tangentialIndex);
        final int t1 = Math.min(t0 + 1, tangentialSize - 1);

        final double distanceWeight = distanceIndex - d0;
        final double radialWeight = radialIndex - r0;
        final double tangentialWeight = tangentialIndex - t0;

        return interpolateCorners(data, d0, d1, r0, r1, t0, t1, distanceWeight, radialWeight, tangentialWeight);
    }

    private static double interpolateCorners(
            final double[] data,
            final int d0, final int d1,
            final int r0, final int r1,
            final int t0, final int t1,
            final double dw, final double rw, final double tw) {

        final double c000 = getValue(data, d0, r0, t0);
        final double c001 = getValue(data, d0, r0, t1);
        final double c010 = getValue(data, d0, r1, t0);
        final double c011 = getValue(data, d0, r1, t1);
        final double c100 = getValue(data, d1, r0, t0);
        final double c101 = getValue(data, d1, r0, t1);
        final double c110 = getValue(data, d1, r1, t0);
        final double c111 = getValue(data, d1, r1, t1);

        final double c00 = lerp(c000, c100, dw);
        final double c01 = lerp(c001, c101, dw);
        final double c10 = lerp(c010, c110, dw);
        final double c11 = lerp(c011, c111, dw);

        final double c0 = lerp(c00, c10, rw);
        final double c1 = lerp(c01, c11, rw);

        return lerp(c0, c1, tw);
    }

    private static double lerp(final double a, final double b, final double t) {
        return a + t * (b - a);
    }

    private static double getValue(final double[] data, final int d, final int r, final int t) {
        return data[toFlatIndex(d, r, t)];
    }

    private static int toFlatIndex(final int d, final int r, final int t) {
        return d * (radialSize * tangentialSize) + r * tangentialSize + t;
    }

    private static double clamp(final double value, final double min, final double max) {
        return Math.max(min, Math.min(value, max));
    }

    private static double applyYawSymmetry(final double yaw, final double tangentialVelocity) {
        return tangentialVelocity >= SYMMETRY_THRESHOLD ? yaw : -yaw;
    }

    private static int calculateTotalElements() {
        return distanceSize * radialSize * tangentialSize;
    }

    private static void logLoadingStart(final String filepath, final boolean verbose) {
        if (!verbose) return;

        final File file = new File(filepath);
        System.out.println("Loading ShootingLookupTable3D from: " + filepath);
        System.out.println("  File size: " + file.length() / BYTES_PER_MEGABYTE + " MB");
    }

    private static void logGridDimensions(final int totalElements) {
        System.out.println("  Grid: " + distanceSize + " x " + radialSize + " x " + tangentialSize + " = " + totalElements + " elements");
        System.out.println("  Divisions: distance=" + distanceDivisions + ", velocity=" + velocityDivisions);
    }

    private static void logLoadingComplete(final long startTime, final boolean verbose) {
        if (!verbose) return;

        final long elapsedMs = System.currentTimeMillis() - startTime;
        final int memoryMB = calculateTotalElements() * 3 * BYTES_PER_DOUBLE / BYTES_PER_MEGABYTE;

        System.out.println("[SUCCESS] ShootingLookupTable3D loaded in " + elapsedMs + "ms");
        System.out.println("  Memory: " + memoryMB + " MB");
    }

    private static void logIfVerbose(final String message, final boolean verbose) {
        if (verbose) {
            System.out.println(message);
        }
    }
}
